[package]
name = "mprs"
version = "0.1.4"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpd = "0.0.12"
colored = "2.0.0"
file = "1.1.2"
